### ISSUE TITLE
Review all COSE parameters and normalize text and integers

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#100]
All our text references should look like:

![Screen Shot 2023-09-19 at 9 51 01 AM](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/assets/8295856/fc7507bc-dd37-4e8c-b68e-a5d5c65270ba)

**Comment by SteveLasker** [comment]
Will align the text, before we cut the draft for 118

**Comment by SteveLasker** [comment]
Missed this one, although we did get some updates. in for 118

**Comment by SteveLasker** [comment]
Closing as subsequent PRs are adopting the formating
