### ISSUE TITLE
Adjust CDDL for Receipts

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#109]
```
~~~~ cddl
claim-label = int / text

; https://www.iana.org/assignments/cwt
claims = {
  &(iss: 1) => tstr 
  ; https://software.vendor or 
  ; did:web:software.vendor
  &(sub: 2) => tstr 
  ; https://software.vendor or 
  ; did:web:software.vendor
  ; https://software.vendor/products/456 or 
  ; did:web:software.vendor:products:456 or 
  ; did:web:software.vendor/products/456 or 
  ; urn:epc:tag:sgtin-96:1.7332402.026591.1234567890
  * claim-label => any
}

statement-protected-header-map = {
  &(alg-id: 1) => int
  &(content-type: 3) => tstr
  &(issuer-key-id: 4) => bstr
  &(issuer-claims: 13) => claims
  * cose-label => cose-value
}

receipt-protected-header-map = {
  &(alg-id: 1) => int
  &(issuer-key-id: 4) => bstr
  &(issuer-claims: 13) => claims
  * cose-label => cose-value
}

~~~~
```

**Comment by henkbirkholz** [comment]
:sparkles:Beautiful:sparkles: Header definitions.

Is `&(issuer-claims: 13) => claims` intended to be mandatory or optional? It could be empty, for example.

**Comment by OR13** [comment]
https://datatracker.ietf.org/doc/draft-ietf-cose-cwt-claims-in-headers/

AFAIK, it can be optional, and it can be empty.

SCITT can make it required, and make it non empty.

I would recommend doing that... reasoning:

`iss` is mandatory, and so the minimum issuer claims includes the issuer's chosen identifier for itself.

hence tag 13 would always be present and inside of it tag 1 would always be present:

https://www.iana.org/assignments/cwt/cwt.xhtml

**Comment by henkbirkholz** [comment]
If there is always a member present in `claims` we could even model that in the data definition, explicitly.

**Comment by OR13** [comment]
I updated the example to include mandatory `iss` and `sub`... and added examples in comments

**Comment by henkbirkholz** [comment]
Ready for transplant into PR, I think

**Comment by SteveLasker** [comment]
closing as stale with addition work to be done
