### ISSUE TITLE
Refine Definition of Feed

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#11]
Copied over from: https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/issues/36

A feed is a great base for how we can create a series of statements for different artifacts, getting freshness for a receipt/or VEX report.
The current definition likely needs to expand a bit to account for:
- What are the versions of a specific artifact
- What are all the statements for a version of an artifact
- What is the latest statement for a specific `contentType` of a specific versioned `artifact`: (eg: what's the latest ~~`SBOM`~~ `application/spdx+json` or  `application/vnd.cyclonedx+json` for the `net-monitor:v1` software?
- If the `contentType` is a referenced [statement by reference](#35), which stores SBOMs, Scan Reports, how do we drill into each if they all use the same payload `contentType` of satementByReference?

**Comment by raylutz** [comment]
I'm not sure if "feed" represents the right concept, when it seems to me that the API to the registry will need to offer the ability to query records for specific orgs-products-models-releases, and collect all the relevant records, which likely include a number of ledger entries to various related artifacts.  With that said, can imagine also the notion of a different API which would provide a feed of updates to the registry, esp. to allow a mirrored version or to perhaps aggregate from several source registries.

**Comment by ad-l** [comment]
> I'm not sure if "feed" represents the right concept, when it seems to me that the API to the registry will need to offer the ability to query records for specific orgs-products-models-releases, and collect all the relevant records, which likely include a number of ledger entries to various related artifacts. With that said, can imagine also the notion of a different API which would provide a feed of updates to the registry, esp. to allow a mirrored version or to perhaps aggregate from several source registries.

This is a good point and one possible improvement that was already brought up at the previous IETF meeting is to enable some structure in the feed header. For instance, using an array of strings would capture many of the common patterns (such as product > model > release), and allow some advanced functions in the API (such as prefix-based querying). Another approach would be to allow each issuer to structure their feed using arbitrary CBOR representations; while this captures many more complex usages (e.g. packages for different Linux distributions, binaries for different architectures) it becomes harder for the transparency service to understand what constitutes related claims (it requires interpretation of the feed format), and thus, harder to define auditing APIs.

**Comment by SteveLasker** [comment]
@ad-l, I've got the notes on feeds and I've been working on a proposal. Would you like to collaborate on it?

Deferring to 117 for prioritization, but a great discussion as many things will be built upon feeds.

**Comment by SteveLasker** [comment]
A note from the [SCITT call on 9/24/2023](https://datatracker.ietf.org/meeting/interim-2023-scitt-34/session/scitt)
We'll be iterating on this a bit more, to create some use cases and examples for how feeds help producers and consumers benefit from SCITT.
