### ISSUE TITLE
Transparent Statement Recursion

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#124]
```
statement -> receipt
statement + receipt => transparent statement^1
transparent statement -> receipt
transparent statement + receipt => transparent statement^2
...
```

There are cases where you want to drop all unprotected data from the signed statement before the registration policy will be applied, and cases where you really want to preserve those unprotected data elements so that the registration policy can be applied.

We need to describe transparent statement inception in detail and comment on its correct usage (and its nonsensical usage).

**Comment by OR13** [comment]
we use code like this, to pull the receipts from the transparent statement, and then we assume that the entry will always have an empty map as its unprotected header... thats not a great assumption, based on the current draft text.

```ts
export const getEntryReceipts = ({ transparentStatement }: RequestEntryReceipts) => {
  const decoded = cbor.decode(transparentStatement)
  let unprotectedHeader = decoded.value[1]
  if (!(unprotectedHeader instanceof Map)) {
    unprotectedHeader = new Map()
  }
  const receipts = unprotectedHeader.get(tags.scitt_receipt) || []
  decoded.value[1] = new Map()
  const entry = cbor.encode(decoded)
  return { entry, receipts }
}
```

**Comment by aj-stein-nist** [comment]
> We need to describe transparent statement inception in detail and comment on its correct usage (and its nonsensical usage).

So how does this happen in the architecture document, is it not an implementation detail? I have become cautious with systems that have unbounded recursion and want sensible limits on "depth." Is that something 1) the group is accepting of 2) even we agree upon it belongs in the architecture doc and not somewhere else?

**Comment by OR13** [comment]
This issue is also related the concept of binding the registration policy to the signed statement... You might set the registration policy as an unprotected header property before adding the signed statement to the log... You will encounter a similar issue.

The problem with unprotected headers, is that they are not protected, so they can contain extra data, such as receipts or registration policies... And a transparency service can strip that stuff out, or inject it, before adding the signed statement to the log.... Tampering with the unprotected header doesn't break the signature, but it does break the inclusion proofs, because it breaks the hash of the entry.

**Comment by SteveLasker** [comment]
> This issue is also related the concept of binding the registration policy to the signed statement... You might set the registration policy as an unprotected header property before adding the signed statement to the log... You will encounter a similar issue.

See: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/136#issuecomment-1879466796

**Comment by SteveLasker** [comment]
Closing as covered in most recent draft 05
