### ISSUE TITLE
Registration and Config statements MUST specify 

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#127]
[Line 635](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/126/files#diff-585fb424519b79cf000445f3425fa56d328cbaca5d2a622740ddc4e5ca91dbe1R635) in PR #126 indicates: 

> The configuration `reg_info` SHOULD include a secure version number and a timestamp.

As these values are considered critical to the stability of the Transparency Service, I made the [comment "To avoid rollbacks, we SHOULD likely make this a MUST, specific to configuration."](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/126/files#r1382909297)

This issue tracks the proposed change

**Comment by aj-stein-nist** [comment]
If we take this proposed change, which one is it?

> The configuration `reg_info` MUST include a secure version number and a timestamp.

or

> The configuration `reg_info` MUST include a secure version number or timestamp.

I do not really know what a "secure version number" could be (do we mean incrementing sequence number?), but just switching SHOULD to MUST and requiring both seems like it could be tedious for the implementer, confusing for a TS Service API client consumer. Barring any guidance, which one is the primary one in the presence of both?

**Comment by SteveLasker** [comment]
Resolved with #135
