### ISSUE TITLE
Add a sequence diagram

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#13]
Copied over from: https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/issues/27

##  Compound User Story / Sequence Diagram

As a consumer, I want to understand if I should trust an artifact
As a producer, I want to be assured that the integrity of my artifacts has been reviewed by a trusted 3rd party.

```mermaid
sequenceDiagram
    participant Issuer
    participant Notary
    Note left of Issuer: I take responsibility for the artifacts I produce
    Issuer ->> Notary: These are the policies I am committed to meeting
    Issuer ->> Notary: I stand by my claims about my artifact
    loop Claims Check
        Notary ->> Notary: Review relevant claims and policies
    end
    Notary ->> Issuer: Here is my endorsement and receipt
    Consumer->>Notary: Is this artifact safe to use?
    loop Endorsement Check
        Notary->>Notary: Review relevant claims and endorsements
    end
     Notary ->> Consumer: You can trust this artifact, the endorsement is still valid
     Note right of Consumer: I have confidence in the artifacts I consume
```

**Comment by SteveLasker** [comment]
This would be a great addition. @OR13, is this something you think you could do for 116? As more folks get connected with SCITT, it might help get started. 
I'll assign 116 for now, but if you don't feel it's realistic, please just reassign 117

**Comment by OR13** [comment]
What is the action? 

To produce ASCII art from the mermaid? 

Open a PR on the architecture with the ASCII art?

**Comment by SteveLasker** [comment]
ASCII Art seems to be the standard for the IETF Specs. @hannestschofenig, what do you think about mermaid?

Should this go in the architecture or the new API draft? Or, maybe the http://scitt.io/ site?

I think it would be a great addition, but you're bringing up a good tooling point.

**Comment by OR13** [comment]
- related issue: https://github.com/mermaidjs/mermaid-live-editor/issues/36

**Comment by SteveLasker** [comment]
Thanks @OR13. I do wonder if it's possible to generate an SVG, similar to [aasvg](https://github.com/martinthomson/aasvg) Was your thought that mermaid could output to aasvg?

**Comment by OR13** [comment]
It is possible to generate svg from mermaid, the problem is that svg does work for ASCII version of RFC, so ASCII art is preferred.

**Comment by SteveLasker** [comment]
Still interesting, bumped to 119

**Comment by SteveLasker** [comment]
@OR13 commits to having a mermaid diagram by our next meeting, or close the issue :)
The challenge is the mermaid doesn't support ASCII Art. Mermaid will allow us to work more quickly
Publish as HTML for draft 05.

**Comment by aj-stein-nist** [comment]
Re #132 I am willing to take this up and do it with aasvg if my other PR in the i-d-template project if that would be helpful.

**Comment by SteveLasker** [comment]
Cost-benefit call - until IETF docs can support a mermaid-like drawing, we'll punt this one.
