### ISSUE TITLE
Mandatory references to policy feeds in receipts

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#136]
Should the policy be committed to in the registration of the signed statement?

Should the policy be committed to in the issuance of the receipt?

Does the commitment need to be in the ledger, or simply in the protected header?

**Comment by OR13** [comment]
related issue: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/66

**Comment by SteveLasker** [comment]
Including the expected policy in the signed statement would require the issuer to know which policy is in effect when they register the statement. While somewhat good to know, it would require the issuer (or the client initiating the workflow) to query the transparency service before registration. This would be an extra call, and check. It would also create a potential race condition or DOS, as the policy could be continually changed, keeping new statements from being registered. 

When the receipt is issued, knowing the registration policy that was applied makes the receipt more valuable. A verifier could decide to accept a receipt for an artifact if the policy is current. A verifier could decide a newer policy invalidates a previous receipt.

Likewise, I'd suggest the ledger should know reflect the policy that was applied at the time of registration. This could be in the unprotected header, as an auditor could correlate the time the statement was registered with the time the policy was in effect. This means you don't lose any security guarantees for the registration policy not being included in the protected header.
