### ISSUE TITLE
What's blocking the architecture?

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#148]
This issue is a living description of the references that block the architecture from becoming an RFC.

```mermaid
flowchart 
    
subgraph COSE
    cometre[draft-ietf-cose-merkle-tree-proofs]
    hash-envelope{{draft-steele-cose-hash-envelope}}
end

subgraph SCITT
    architecture[draft-ietf-scitt-architecture]
    scrapi{{draft-birkholz-scitt-scrapi}}
    cometre-ccf{{draft-birkholz-cose-cometre-ccf-profile}}
end

scrapi --> architecture
architecture -->  cometre
architecture --> hash-envelope
cometre-ccf --> cometre
```

Currently, the `draft-ietf-scitt-architecture` is blocked by `draft-ietf-cose-merkle-tree-proofs`.

`draft-steele-cose-hash-envelope` is not blocking anything because it is just a special kind of signed statement, its possible it might block `draft-birkholz-scitt-scrapi` in the future.

`draft-birkholz-cose-cometre-ccf-profile` is blocked by `draft-ietf-cose-merkle-tree-proofs`

I recommend helping `draft-ietf-cose-merkle-tree-proofs` close out so the architecture can be published.

I would then make `draft-birkholz-scitt-scrapi` adopted by SCITT, and make it be blocked by the architecture.

**Comment by SteveLasker** [comment]
Thanks, @OR13
While I believe `draft-steele-cose-hash-envelope` is important to support, it's not clear it needs to be in the architecture, although it's currently tied to the identity discussion. #145

With #149 complete, we can now invert SCRAPI to be dependent on the Architecture.

```mermaid
flowchart 
    
subgraph COSE
    cometre[draft-ietf-cose-merkle-tree-proofs]
    hash-envelope{{draft-steele-cose-hash-envelope}}
end

subgraph SCITT
    scrapi{{draft-birkholz-scitt-scrapi}}
    architecture[draft-ietf-scitt-architecture]
    cometre-ccf{{draft-birkholz-cose-cometre-ccf-profile}}
end

scrapi --> architecture
architecture -->  cometre
architecture --> hash-envelope
cometre-ccf --> cometre
```

**Comment by OR13** [comment]
I updated the issue description diagram to reflect the current state.

If folks like I can add blockers to the architecture based on major open issues next, so we can see how "identifiers" and "configuration" are related to finishing the architecture.

**Comment by SteveLasker** [comment]
> If folks like I can add blockers to the architecture based on major open issues next, so we can see how "identifiers" and "configuration" are related to finishing the architecture.

Tracking the blockers is goodness. I've added #151

**Comment by henkbirkholz** [comment]
> If folks like I can add blockers to the architecture based on major open issues next, so we can see how "identifiers" and "configuration" are related to finishing the architecture.

My individual summary of potential content/decision blockers (in contrast to reference blockers) as far as I am aware of them. Some of them might already have consensus, but it is not reflected, I think:

* Text on identity document use in SCITT. My assumption is: agnostic expositional text and at least one example how to use x.509 wrt Signed Statements and Receipts
* Text on statement identification. My assumption is that we need at least abstract exopsitional text. I am not sure, if this can/will be part of the first iteration of the architecture document.
* Meaning of subject tstr composition (formerly known as feed). My assumption is: we are only providing the tstr in the CDDL definition of the Receipt structure and highlight in English text that SCITT CoMETRE profiles, such as https://datatracker.ietf.org/doc/draft-birkholz-cose-cometre-ccf-profile/ to remove that burden from the architecture I-D

**Comment by SteveLasker** [comment]
Resolved the loose ends

**Comment by aj-stein-nist** [comment]
How did we resolve loose ends on dependent drafts where the RFCs aren't past WGLC in other WGs?
