### ISSUE TITLE
Registration Information data in Protected Header needs to be consistent

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-wg-scitt/draft-ietf-scitt-architecture#154]
Registration_Info is defined in the protected header is not aligned properly to 
Statement Registration Information (Statement_Registration_info) mentioned in the document!

**Comment by OR13** [comment]
I read this again, and it seems the intention is to include unsecured data in the unprotected header.

Per the changes in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/145

That information will not be included in the identifier, and I would like to see use cases for it, or to see it removed.

**Comment by henkbirkholz** [comment]
The rough consensus seems to lean towards removing statement identifiers out-of-scope of the core SCITT architecture. Are there any objections to that wrt this issue?

**Comment by SteveLasker** [comment]
Addressed in 05
