### ISSUE TITLE
Signed statement identifier should be hash

### ISSUE THREAD

**Issue by aj-stein-nist** [ietf-wg-scitt/draft-ietf-scitt-architecture#155]
Per authors meeting today: update the architecture such that the content identifier of the SCITT receipt for SCITT signed statement shall be the hash of the to-be-signed bytes as defined by COSE specification.

**Comment by SteveLasker** [comment]
Adding a bit more clarity. 
The hash shall be of the protected header and payload. The unprotected header is stripped to assure consistency

**Comment by henkbirkholz** [comment]
How much is this issue related to #167?

**Comment by SteveLasker** [comment]
Resolved in 05
