### ISSUE TITLE
New Examples for new section "Support for Multiple Statements"

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-wg-scitt/draft-ietf-scitt-architecture#160]
Looking at https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/153/, I think a that some more diverse examples later that show how multiple statements about one Artifact using the same sub Claim can have different semantics than multiple statements about one Artifact using different sub Claims - including illustrating text when one choice can be used an when the other & pros and cons.

**Comment by SteveLasker** [comment]
Covered above
