### ISSUE TITLE
Define error codes

### ISSUE THREAD

**Issue by letmaik** [ietf-wg-scitt/draft-ietf-scitt-architecture#17]
From https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/3#discussion_r1114223387.

More error codes should be defined.

**Comment by SteveLasker** [comment]
@letmaik, with the focus to pull the API into another draft, should we close this, or transfer?

**Comment by SteveLasker** [comment]
Closing as this is likely part of [SCRAPI](https://github.com/ietf-scitt/draft-birkholz-scitt-scrapi/)
