### ISSUE TITLE
Converge Media Type, Content Type, Payload Type

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#178]
The doc uses the three interchangeably
Is there a preferred reference to be consistent?

**Comment by SteveLasker** [comment]
https://www.rfc-editor.org/rfc/rfc6838 is about Media Type. And then references payload and content type. 
I've been through this confusion before, where Media Type is the definition of a type of identifier. The challenge becomes when using that type of identifier for different parts of a document. 
- When does the media type refer to the envelope itself? 
- When does the media type refer to a property (aka payload)?

**Comment by OR13** [comment]
I don't understand the question.

`cose-sign1.cbor` is of content type `application/cbor` and `application/cose` .

It is generally a good idea to use a more specific media type.
