### ISSUE TITLE
Statement by reference

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#18]
Copied over from: https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/issues/35

At IETF 115 there were discussions on having some kind of standard way to deal with statements by reference. Here are also the two relevant slides from https://datatracker.ietf.org/doc/slides-115-scitt-combined-scitt-presentations/:

**Comment by SteveLasker** [comment]
Reluctantly moving beyond 116. We do have some new work for clarifying statement types, but it won't be ready for 116 proper. 

If someone has bandwidth to focus upon for the 116 hackathon, please grab this. In lieu of that, I'm differing for now.

**Comment by SteveLasker** [comment]
Statement by reference is still assumed through discussions, but not yet captured in the specs. Moving to 119

**Comment by OR13** [comment]
https://github.com/OR13/draft-steele-cose-hash-envelope

**Comment by OR13** [comment]
^ work in progress, will need to got to COSE WG, its an "attached payload" where the payload is a hash and the header has hash specific meta data.

**Comment by SteveLasker** [comment]
Noting that I believe supporting detached payloads, with a hash, is important to the first submission of the Architecture document.

**Comment by SteveLasker** [comment]
Addressed in the appendix of draft 05
