### ISSUE TITLE
Are signed statements returned from a TS or only Receipts?

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#183]
Our implementation only returns receipts, because our log only stores hashes, you would need to call a different adjacent service to get the "original contents"... other implementations may have co-located these APIs and might support delivering more than "receipts" from a TS.

Based on 

- https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/179/files#r1484545650
- https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/179/files#r1483686978

**Comment by SteveLasker** [comment]
Closing as resolved in 05, returns receipts
