### ISSUE TITLE
make this an editor comment

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-wg-scitt/draft-ietf-scitt-architecture#184]
make this an editor comment

_Originally posted by @ad-l in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/179#discussion_r1484498187_

**Comment by yogeshbdeshpande** [comment]
To be completed!

**Comment by SteveLasker** [comment]
Closing as resolved in 05
