### ISSUE TITLE
Authorization of the issuer is missing!

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-wg-scitt/draft-ietf-scitt-architecture#186]
so the authorization of the Issuer and of the Transparency Service by the Verifier of the Receipt are generally independent

_Originally posted by @yogeshbdeshpande in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/179#discussion_r1484586471_

**Comment by ad-l** [comment]
See also #200

**Comment by SteveLasker** [comment]
Resolved by #197
