### ISSUE TITLE
But at least their intended security properties are? If this is out of scope of SCITT then at least the COMETRE document must be much more specific about the minimum security properties of verifiable data structures.

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-wg-scitt/draft-ietf-scitt-architecture#187]
But at least their intended security properties are? If this is out of scope of SCITT then at least the COMETRE document must be much more specific about the minimum security properties of verifiable data structures.

_Originally posted by @ad-l in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/179#discussion_r1484523409_

Address comment from Cedric

**Comment by SteveLasker** [comment]
@ad-l can you trim this title down to something actionable and propose a PR for changes?

**Comment by ad-l** [comment]
This is explained in more detail in #199
