### ISSUE TITLE
That is a big TODO and since x5t is now mandatory it needs to be specified before this PR can be merged

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-wg-scitt/draft-ietf-scitt-architecture#188]
That is a big TODO and since x5t is now mandatory it needs to be specified before this PR can be merged

_Originally posted by @ad-l in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/179#discussion_r1484526507_

**Comment by aj-stein-nist** [comment]
Is it in fact the case that `x5t` use is mandatory in the draft spec and this issue is to track follow-on edits? Or is this issue to confirm whether or not that is the case and adjust accordingly?

**Comment by ad-l** [comment]
This is detailed in #200
