### ISSUE TITLE
Discuss the possible issue on Client not the same as Issuer

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-wg-scitt/draft-ietf-scitt-architecture#189]
Discuss the possible issue on this issue!

_Originally posted by @yogeshbdeshpande in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/179#discussion_r1484610979_

**Comment by SteveLasker** [comment]
Please propose a PR.

**Comment by SteveLasker** [comment]
I realized @yogeshbdeshpande is OOF this week, so I submitted #197

**Comment by SteveLasker** [comment]
resolved by #197
