### ISSUE TITLE
Revisit Validation section for clarity after refactoring PR

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-wg-scitt/draft-ietf-scitt-architecture#190]
Revisit ### Validation {#validation} section fully: After refactor

_Originally posted by @yogeshbdeshpande in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/179#discussion_r1484614307_

**Comment by SteveLasker** [comment]
Please propose a new PR.
