### ISSUE TITLE
Resolve inconsistencies with what's stored and returned in the Append-only Log

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#192]
Registration referred to persisting and returning a transparent statement. The latest doc (Feb 9, 2024) starts to focus on storing and returning receipts, keeping the signed statements separable and possibly stored in associated data structures. A Transparent Statement is not something directly in the Append-only Log. However, the architecture has remnants that may not be completely agreed upon. 

For example:
> Register the Signed Statement to the append-only log
> 
> Return the Transparent Statement, which includes the Receipt Details about generating Receipts are described in [Section 6.4](https://ietf-wg-scitt.github.io/draft-ietf-scitt-architecture/draft-ietf-scitt-architecture.html#Receipt).

and

> Some jurisdictions have a Right to be Forgotten. However, once a Signed Statement is inserted into the Append-only Log maintained by a Transparency Service, it cannot be removed from the Log.

and

> [7.2.3. ](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/192#section-7.2.3)[Confidentiality and Privacy](https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/192#name-confidentiality-and-privacy)
According to Zero Trust Principles any location in a network is never trusted. All contents exchanged between actors is protected using secure authenticated channels (e.g., TLS) but may not exclude network traffic analysis.
> 
> The Transparency Service is trusted with the confidentiality of the Signed Statements presented for Registration. Some Transparency Services may publish every Signed Statement in their logs, to facilitate their dissemination and auditing.

**Comment by OR13** [comment]
Transparent statements can go on a log, if they are COSE sign 1 and they are accepted by a registration policy.

Saying anything other than that will likely require, nontrivial adjustments to our definitions.

**Comment by SteveLasker** [comment]
Closing as resolved in 05 (receipts)
