### ISSUE TITLE
Restore log consistency & append-only requirements in architecture (4.1.3)

### ISSUE THREAD

**Issue by ad-l** [ietf-wg-scitt/draft-ietf-scitt-architecture#199]
After the refactor, the only remaining normative text about the append-only log (4.1.3) states:

> The security properties of the Append-only Log are determined by the choice of the verifiable data structure used to produce Receipts.
> [...]
> Specific verifiable data structures, such those describes in [[RFC9162](https://www.rfc-editor.org/rfc/rfc9162)] and [[I-D.draft-steele-cose-merkle-tree-proofs](https://datatracker.ietf.org/doc/html/draft-steele-cose-merkle-tree-proofs-01)] are out of scope for this document.

There are currently no requirements for verifiable data structures used for the ledger, so indeed it is possible to define and implement a ledger that is non consistent. In fact even though it is called an "append-only ledger" there is no normative requirement in the architecture or in COMETRE that the verifiable data structure is append-only. This is also incompatible with the definition of transparency in section 3 that states:

> Transparency is implemented by providing a consistent, append-only, cryptographically verifiable, publicly available record of entries.

Given that auditable consistency is part of the definition of transparency, the security properties of acceptable verifiable data structures should be specified:
- either in the architecture document itself, as it was before version 05
- or, as a requirement for defining new verifiable data structures in I-D.draft-steele-cose-merkle-tree-proofs

**Comment by fournet** [comment]
I believe this is a core requirement that should be clearly stated in the SCITT architecture (even if its implementation is delegated to other specs such as COMETRE). Without it, I find it hard to argue about its security and transparency benefits.

**Comment by OR13** [comment]
We discussed this issue on the call.

We determined that there should be a pull request raised, which states:

SCITT Receipts MUST support inclusion proofs, and MAY support consistency proofs.

SCITT does not require a specific verifiable data structure.

It is RECOMMENDED that verifiable data structures used for SCITT Receipts receive public cryptographic review on CFRG or similar.

**Comment by OR13** [comment]
This issue will be closed if no PR is raised by Friday.

**Comment by aj-stein-nist** [comment]
> It is RECOMMENDED that verifiable data structures used for SCITT Receipts receive public cryptographic review on CFRG or similar.

Just to be clear because I was unable to attend the call: this is a procedural point and will not be explicitly written into the draft with a PR? I assume not, but I thought it was worth clearing up.
