### ISSUE TITLE
Consumer is a capitalized term but not defined

### ISSUE THREAD

**Issue by aj-stein-nist** [ietf-wg-scitt/draft-ietf-scitt-architecture#206]
As part of #120, I would like to consider the removal of Consumer and consumer from this specification if we are not going to define it. It is a generalized term and I would rather expend work group time on trying to tailor an appropriate custom definition of it.

I will likely post this issue to the mailing list and cross-reference that thread here and leave this issue for review for a week to solicit feedback.

Related mailing list thread: https://mailarchive.ietf.org/arch/msg/scitt/yTaAi3l-q2TZVLNH4Wp36rR232Q/.

**Comment by SteveLasker** [comment]
I do think Producer and Consumer is a good generic concept, with more clearly defined roles as Relying Party, Verifier, and Auditor, however, I'd support replacing Consumer with Relying Party or Verifier.

**Comment by aj-stein-nist** [comment]
> I do think Producer and Consumer is a good generic concept

But we do not define them nor cite references that do. From a formality and procedures perspective in IETF, is that OK?

> I'd support replacing Consumer with Relying Party or Verifier.

Thanks for the feedback.
