### ISSUE TITLE
Security Assurances to Auditors

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#214]
There is ongoing discussion regarding what properties are assured for auditors, based on normative requirements in the specification:

https://mailarchive.ietf.org/arch/msg/scitt/28wIM5UhewqFm0sPIVpHpQ2-DwM/

We need to be more precise regarding what "auditable" means.

Does it ONLY mean that a merkle tree can be reconstructed?

or does it mean that a merkle tree can be reconstructed AND the policies included in it can be confirmed to have been applied based on the content of the log. (does it enable use cases where signatures MUST be verified).

**Comment by raylutz** [comment]
Probably the notion can be split into several different levels.

1. Internal consistency "review" -- That would relate to checking that the tree is consistent at least to some extent. A review may not check the entire tree for consistency, but it may have to. Checking consistency of the entire tree would still be at this  level.

2. Artifact consistency -- without understand the data, check that the hash is still generated when applied with any specified salt and that it matches what is in the tree.

3. External consistency -- Checking back to source information like trust anchors to verify all signatures are correct, etc.

Maybe this is helpful.

**Comment by ad-l** [comment]
The current stance of the architecture document (after #213) is that the minimum policy (checking the statement's signature and authenticating the issuer) has to be fully auditable based on the log and/or the receipt, barring some exceptional circumstances.

I am in favour of extending the same requirement to the rest of the registration policy - an auditor should be able to check based on the log + receipt that the TS applied the registration policy correctly. However, there are some known challenges related to this; it is likely that some policies will be stateful (which may be OK if the state is pulled from the log), but some TS may perform side effects such as HTTP requests to evaluate policies which makes the auditing more complicated unless a lot more ad hoc information is added to the log.

I think our high level goal is to facilitate interoperability of auditing, i.e. an auditor should be able to verify the registration of a transparent statement regardless of which implementation the TS on which it was registered is using. This may be realistically achievable for the signature validation, but hard for arbitrary stateful registration policies unless we put additional constraints, such as requiring that all extra inputs of a registration policy and state mutations must rely on the log, and no other state. This would certainly be very constraining for implementers and many would probably give up on using auditable registration policies altogether.

**Comment by robinbryce** [comment]
Is auditability really such a binary concept ? Is it possible to frame auditable registration with more nuance: For example: "is autidable with the public key material in the log", "is auditable assuming the retention policy of this external source" and so on.

Boiling that down in spirit: The TS is required to make it clear _how_ auditable the log & receipts are, and precisely what it offers. Rather than have the arch only work for a very rigid constraints, which might be pretty challenging to agree on anyway.

**Comment by OR13** [comment]
On the call today, there was consensus that draft text for auditors is good enough.

I propose closing this issue.

**Comment by SteveLasker** [comment]
As discussed in the Architecture Editors call, and believe the document is auditable and we can close this issue.

**Comment by raylutz** [comment]
I believe the architecture provides a viable basis for auditing that can be expanded as needed in the future. Okay to close.

**Comment by OR13** [comment]
I'm closing this based on the feedback and discussion.
