### ISSUE TITLE
Incorporate cose-merkle-tree-proofs replacing SCITT Receipts

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#22]
[cose-merkle-tree-proofs](https://github.com/ietf-scitt/cose-merkle-tree-proofs)

**Comment by SteveLasker** [comment]
As we're working to complete [draft-steele-cose-merkle-tree-proofs](https://github.com/ietf-scitt/draft-steele-cose-merkle-tree-proofs) for 116, I'm assigning to 116

**Comment by ad-l** [comment]
See #68 for a proposed implementation

**Comment by SteveLasker** [comment]
Closing as #68 has been merged
