### ISSUE TITLE
Should we add Registered Signed Statement to the terminology

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#221]
The TS stores Signed Statements. When we started SCITT, I believe several folks had the position that TS would create and store Transparent Statements. 
As of draft 06, a Transparent Statement is assembled on the client, outside the scope of the TS. Yet, we still refer to Transparent Statements. 
Should we add a term called Registered Signed Statement, which differentiates a Signed Statement that hasn't yet been registered, and a Signed Statement that has been registered, but isn't Transparent as the TS doesn't staple the receipt to the Signed Statement?

**Comment by SteveLasker** [comment]
>This change was intentional and explicitly stated in 06?

Correct, we did clarify a Transparent Statement is assembled outside the Transparency Service, or more specifically, outside the SCITT API/Architecture. 
An implementation could assemble them. 
However, reading and writing new docs, it's become difficult to describe a signed statement that's been registered. See: https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi/pull/5/commits/6a81982412e1eb8c87545f25def8311c8beee013

If others agree, proposal would be to add Registered Signed Statement in the terminology and other relevant places in the doc.

**Comment by bobmartin3000** [comment]
Sounds like a good change

**Comment by raylutz** [comment]
I would prefer to see that the format of the final registered signed statement be defined because it appears that this will be likely something that is published along with an artifact in many use cases.

**Comment by SteveLasker** [comment]
Consider re-wording a transparent statement as a state that comes after registration and the append-only log. Not just when it's stapled to the signed statement

**Comment by SteveLasker** [comment]
Closing as the group felt we didn't need another definition.
