### ISSUE TITLE
DNS Name Compatible Receipt Identifiers

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#224]
Consider:

```
urn:ietf:params:scitt:receipt:sha-256:base64url:5i6UeRzg1...qnGmr1o
```

While this provides string name that works ok for HTTP APIs, this name is not acceptable in many other APIs, due to its use of multiple cases and the colon character.

Consider a CSR which wishes to obtain a certificate with a SAN, where the SAN can encode a fully qualified receipt.

Possible syntax:

```
receipt-{lowercase(base64url(sha256(signed-statement)))}.transparency.service.example
receipt-{lowercase(hex(sha256(signed-statement)))}.transparency.service.example
```

`receipt` could be shortened.

Names can't start with numbers, cant include special characters, etc...

In the same way that URN authority moves left to right, DNS name authority moves right to left... right?

There would be issues with case collisions, perhaps base16 lowercase is a better choice.

There are restrictions on the max length of SANs, we would want to check those.
 
Is this an abuse of SAN? 

Being "name" lookup compatible with DNS seems worth considering.

**Comment by JAG-UK** [comment]
I'm not fully sure I'm following, but I think I'm leaning towards the 'abuse of SAN' answer. 

Do I understand that you want to somehow encode an (Issuer?) identity (or some statement about an identity ... and yes I've deliberately avoided the word 'claim' here) into a SCITT Signed Statement, then get a SCITT Receipt for that and then put the whole Receipt in the SubjectAltName field so that the identity coms ready-loaded with some kind of provenance/authenticity measure in it?

**Comment by OR13** [comment]
For `sub` and `iss`, the value `example.com` is an acceptable value, and an acceptable SAN.

And yes, long story short, I am wondering about where Receipts might be provided by reference in CSRs... similar to how Let's Encrypt certificates contain references to SCITs, and support SANs.

**Comment by OR13** [comment]
See https://wiki.mozilla.org/Security/Binary_Transparency for an example of this

**Comment by aj-stein-nist** [comment]
> See https://wiki.mozilla.org/Security/Binary_Transparency for an example of this

Thanks for finding this, I was searching email and Slack and could not find what software/group used this is when you posted but I swore I had seen it. There it is!

**Comment by SteveLasker** [comment]
As discussed on the call, deferring at this point.
