### ISSUE TITLE
Automate summarizing issues and PRs to the SCITT mailing list

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#228]
Vote with +1 for automating this, making the changes more visible to folks tracking the mailing list

**Comment by JAG-UK** [comment]
+1

**Comment by aj-stein-nist** [comment]
I haven't heard back from those in the know but I may just try [to mimic the code recommended to Steve by others in the Slack](https://github.com/ietf-github-services/issue-summary) accordingly. I guess I have to figure out which email credentials I can use to send it for this GH org, but that will come later.

**Comment by SteveLasker** [comment]
Thanks, @aj-stein-nist for taking this up.

**Comment by aj-stein-nist** [comment]
Apologies for the delay, see the upstream PR in the relevant IETF services repo linked below.

https://github.com/ietf-github-services/activity-summary/pull/69

**Comment by SteveLasker** [comment]
Thank you @aj-stein-nist
