### ISSUE TITLE
Clarification: Notarization is not the process of creating a signed statement

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#23]
I don't love this language.

I think notarizing applies to making a "Signed Statement" a "Transparent Statement"... but this sentence seems to imply notarization is part of the process of creating a "Signed Statement", which seems wrong.

_Originally posted by @OR13 in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/16#discussion_r1126710441_

**Comment by SteveLasker** [comment]
@yogeshbdeshpande, is it realistic to get some clarification in by this Friday so we can review and merge by Monday?

**Comment by nealmcb** [comment]
For context, I think this is the _language_ in question:

> If trust can be put into the operations that record Signed Statements (i.e., a believable notarization function) in a secure, append-only Registry via online operations, the same trust can be put into a corresponding Receipt that is the resulting documentation of these online operations issued by the Transparency Services and that can be validated in offline operations.

**Comment by OR13** [comment]
^ yes, that is it.

I prefer something closer to:

> The issuer of a signed statement should been authenticated, and trusted to make the statements according to a registration policy for the transparency service. The issuer of a receipt for a transparent signed statement  (i.e., a believable notarization function), when trusted as a notary facilitates offline verification ... etc...

**Comment by nealmcb** [comment]
I've heard a lot of agreement that questions of trust should be placed clearly in the consumer's court. If they choose to categorically believe statements from any particular Issuer or Transparency Service, that's up to them. But given the variety of threat models and requirements out there, others will require multiple independent pieces of evidence, or will distrust those parties, and instead trust others.
So we should stay away from phrasing which associates universal trust with actors or services, and instead present it from the consumer's perspective.

Given the context, which focuses mainly on the relationship between online and receipt-based verification, how about this:

> For a given consumer who would trust a set of Signed Statements from a particular Transparency Service via online operations, we provide for a Receipt countersignature which should allow them to trust the corresponding Receipt, issued by the Transparency Service for those online operations, if if they can be validated in offline operations.

**Comment by SteveLasker** [comment]
Closing as stale. If the [current draft](https://datatracker.ietf.org/doc/draft-ietf-scitt-architecture/) doesn't reflect the needs, please open a new issue, and/or PR
