### ISSUE TITLE
Register unsigned artifacts?

### ISSUE THREAD

**Issue by raylutz** [ietf-wg-scitt/draft-ietf-scitt-architecture#238]
Recent CISA/NIST work creates a self-attestation for software, which is not signed. This can't be easily submitted to SCITT without prior signing, but it is a gap in the current capabilities at most orgs creating a digital signature. Need to either find a way for orgs to easily sign the artifact, allow unsigned artifacts in SCITT, or ??

https://www.cisa.gov/resources-tools/resources/repository-software-attestations-and-artifacts-rsaa-user-guide

https://www.cisa.gov/sites/default/files/2024-03/CISA_RSAA_User_Guide_18_March_2024.pdf

and they use this self-attestation form:
https://www.cisa.gov/sites/default/files/2024-03/Self-Attestation-Common-Form-03082024-FINAL.pdf

**Comment by SteveLasker** [comment]
Thanks, @raylutz,
This was discussed as part of SCRAPI, where a Transparency Service could implement signing on-behalf of the user, based on their identity to the service. This would be consistent with the architecture, where the statement is signed. It's just a matter of whether it's signed on ingress to the service, before being registered on SCITT. 
Suggest moving this to [SCRAPI](https://github.com/ietf-wg-scitt/draft-ietf-scitt-scrapi).

**Comment by SteveLasker** [comment]
Closing to discuss in SCRAPI
