### ISSUE TITLE
Clarification: add notarization

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#24]
I think the concept of "notarization" needs to go here... or it needs to not be used anywhere.

_Originally posted by @OR13 in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/16#discussion_r1126712923_

**Comment by SteveLasker** [comment]
@OR13, is this a quick item for 116?

**Comment by OR13** [comment]
Possibly, what role do we assign the "issuer" of a transparent statement.

How do we distinguish issuing a transparent statement, from issuing a signed statement.

What policies apply to transparent statements vs signed statements?

Do we think the word notary is useful?

Is the notary the name for identity that signs a transparent statement?

**Comment by SteveLasker** [comment]
Roles is a good loaded word. 
Some thoughts:

- A signed statement is signed by the issuer, external to the Transparency Service. 
- After the registration policy has been completed, the signed statement gets notarized and becomes a transparent statement.
- It's the process of completing the registration policy which implies being notarized.
- As we start to define how a SCITT Transparency Service would be configured, it does seem like the identity of the notarization process would be a Notary.

**Comment by nealmcb** [comment]
I'm a fan of the recommendation to use the term registered statement rather than transparent statement. If we adopt that, it would seem clearer to use the term registrar rather than overloading the term notary in a way that seems novel to me. Are there examples in other areas where different notaries follow different registration policies?

**Comment by SteveLasker** [comment]
Closing as stale, and the current draft has been updated quite a bit.
Please re-open if new text is needed.
