### ISSUE TITLE
Make CDDL definitions separate files and import to draft

### ISSUE THREAD

**Issue by aj-stein-nist** [ietf-wg-scitt/draft-ietf-scitt-architecture#244]
As an implementer, in order to directly use the CDDL definition(s) without having to extract the definitions with custom code or copy-pasting, I would like if the source code and tools in this repository to define the CDDL definitions as discrete files and import them the Kramdown RFC mechanisms, so my code can you the CDDL directly without those steps.

See `{::include ...}` directives from other sample drafts, [such as the current CBOR EDN Literals I-D](https://github.com/cbor-wg/edn-literal/blob/a5f3cb1f115f9d5adae812e3f38a0451f233c4a3/draft-ietf-cbor-edn-literals.md).

**Comment by aj-stein-nist** [comment]
If others do not object and/or would find this useful, I am voluteering to open a PR to make this change later this week.

**Comment by SteveLasker** [comment]
@aj-stein-nist, there's a comment of concern we're not at this point of complexity, but we're open to viewing a PR to try this change.

**Comment by aj-stein-nist** [comment]
> @aj-stein-nist, there's a comment of concern we're not at this point of complexity, but we're open to viewing a PR to try this change.

OK, good thing it was not complex. https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/247 is ready for review.
