### ISSUE TITLE
Clarification: "DID Key Manifest" to another term

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#25]
I suggest maybe not using the words "DID Key Manifest"... 

Maybe "Public Key Identifier" or "VerificationMethod".

_Originally posted by @OR13 in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/16#discussion_r1126717438_

**Comment by SteveLasker** [comment]
Deferring to 117 as it's a good clarification as we dig deeper into registration policy, but doesn't seem a priority for 116

**Comment by SteveLasker** [comment]
@OR13 do you want to take another look at this? Or shall we close due to inactivity?

**Comment by OR13** [comment]
The latest PR has several related corrections, I can't say if additional changes are needed but I am fine closing this issue
