### ISSUE TITLE
"Agility" Parameter

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-wg-scitt/draft-ietf-scitt-architecture#264]
>   In order to accommodate as many Transparency Service implementations
   as possible, this document only specifies the format of Signed
   Statements (which must be used by all Issuers) and a very thin
   wrapper format for Receipts, which specifies the Transparency Service
   identity and the **agility parameters** for the Signed Inclusion Proofs.

What is an agility parameter?

**Comment by SteveLasker** [comment]
If this reflects the latest text, please make a PR.
