### ISSUE TITLE
TLS not mandated by the architecture

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-wg-scitt/draft-ietf-scitt-architecture#291]
> All contents exchanged between actors is protected using secure authenticated channels (e.g., TLS) but may not exclude network traffic analysis.

This sentence in the security consideration section gives the reader the impression that communication security is assumed to be used. This is, however, not even discussed in the body of the document.

**Comment by JAG-UK** [comment]
> Does the TLS requirement belong in the architecture or SCRAPI?

The architecture document needs a Security Considerations section. What is in that section is of course up to the authors.

**Comment by JAG-UK** [comment]
I think a deeper issue is that it's not clear that an authenticated channel _is_ actually required in most cases. The Signed Statement is inherently integrity protected and carries strong Issuer identity so then we come down to questions that are definitely SCRAPI-specific (and SCRAPI has a Security Considerations already) and/or make recommendations focused more on confidentiality only

**Comment by aj-stein-nist** [comment]
> I think a deeper issue is that it's not clear that an authenticated channel _is_ actually required in most cases.

I was going to counter with some whataboutism and say "what about RFC9162!?" but it seems you are right. In the Security Considerations and elsewhere they never really explicate that, so your point stands.

I guess I would be interested in how this "frees up" TS instances conformant to the architecture that do not strictly use HTTPS and TLS a la SCRAPI, but that is outside the scope of this document and SCRAPI too, so I will leave my comment there for now. 😄

**Comment by SteveLasker** [comment]
Proposing we close, and leave TLS to be API specific (aka SCRAPI)

If no objections, or more specifically no PRs are submitted by Oct 8, 2024, I propose we close this issue.

**Comment by aj-stein** [comment]
> Proposing we close, and leave TLS to be API specific (aka SCRAPI)
> 
> If no objections, or more specifically no PRs are submitted by Oct 8, 2024, I propose we close this issue.

I support closing it out, and I can support waiting until October 8th as well. :smile:
