### ISSUE TITLE
Clarification: how does the Transparency Service ensure determinism?

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#31]
how does the TS ensure determinism?

_Originally posted by @nedmsmith in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/16#discussion_r1123538125_

**Comment by nealmcb** [comment]
Duplicate of #35

**Comment by SteveLasker** [comment]
Thanks @nealmcb, for helping reduce the total number of issues
