### ISSUE TITLE
Clarification: How does a Transparency Service ensure determinism?

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#35]
how does the TS ensure determinism?

_Originally posted by @nedmsmith in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/16#discussion_r1123538125_

**Comment by SteveLasker** [comment]
Deferring to 117 as I suspect this will take a lot of discussions that won't land by 116.

**Comment by pdxjohnny** [comment]
Potentially related: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/79#issuecomment-1767445443

**Comment by SteveLasker** [comment]
Closing as stale, with the link to #79 as a possible updated tracking item.
Please re-open if needed, with additional context.
