### ISSUE TITLE
Clarification: Define consumer

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#39]
From a terminology perspective, "consumer" can mean:
- End users that "consume" software, akin to a consumer of purchased good and services
- Anyone interacting with a SCITT Transparency Service - akin to publishers and consumers of a SCITT Transparency service

Suggestion for tracking: add "Consumer" to the [Terminology](https://ietf-wg-scitt.github.io/draft-ietf-scitt-architecture/draft-ietf-scitt-architecture.html#name-terminology) section

              'consumer' might not be the best term. Does it mean ingress or someone engaging in commerce?

_Originally posted by @nedmsmith in https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/16#discussion_r1123549835_

**Comment by SteveLasker** [comment]
The header under terminology has been added. It now needs the details.
Adding to 116, as this may be small enough to agree a Consumer is someone that interacts with a SCITT Transparency Service. If it takes a lot of discussion, we'll defer to 117

**Comment by nealmcb** [comment]
Yes, simply define as one who interacts with a SCITT service.

**Comment by SteveLasker** [comment]
There are references in the doc, as is. Deferring to 117, to create stability for 116.

**Comment by SteveLasker** [comment]
Completed
