### ISSUE TITLE
Consolidate Log and Ledger

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#46]
The architecture terminology refers to:

**Registry:** the verifiable append-only data structure that stores Signed Statements in a Transparency Service often referred to by the **synonym log or ledger**. 

To minimize concept counts, and avoid confusion with diagnostic logs, shall we use Ledger as the persistent form of the Transparency Service?

**Comment by henkbirkholz** [comment]
I am not sure, that we are in a place to declare a winner. Maybe there is a chance to resolve this issue on the Monday meeting. I am not overly optimistic as more important changes are in the cue.

**Comment by SteveLasker** [comment]
Agreed. Log wasn't used very much, and while I understand the use of "log" for the persistence of statements, @nedmsmith highlighted a section that made me wonder if we were tossing failed registration into a diagnostics log, or placed on a RBAC enabled ledger.

To your point, I left this open as it warrants discussion.

**Comment by SteveLasker** [comment]
Closing, in lieu of #60
