### ISSUE TITLE
Do we need dedicated section on SCITT requirements for append-only log?

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-wg-scitt/draft-ietf-scitt-architecture#67]
Maybe the term "append-only log" is self-descriptive and technology-agnostic enough by itself or maybe a set of examples is helpful.

**Comment by fournet** [comment]
Examples could help, as long as we are not too demanding on implementations (notably on their need to commit & persist statements before issuing receipts, on serializability, on replication). This was controversial in several discussions so far.

**Comment by raylutz** [comment]
I believe there is some functionality that is required that is not encompassed by the notion of an append only log:
1. Ability to somehow tag and group items, perhaps to simulate the ability to add to an existing set of entries. For example, incremental cryptographic data as a larger data set is being built, or another example is test data that is applied later.

**Comment by SteveLasker** [comment]
Closing as stale, and belief we've captured this. 
Please open new Issues/PRs with new new specific needs
