### ISSUE TITLE
Terminology: Registry & Transparency Service 

### ISSUE THREAD

**Issue by SteveLasker** [ietf-wg-scitt/draft-ietf-scitt-architecture#7]
Copied over from: https://github.com/ietf-scitt/draft-birkholz-scitt-architecture/issues/38

The architecture I-D, and other docs use Registry and Transparency Service (TS) interchangeably. 

This issue is about consistent naming, and what we should use for an implementation that hosts the SCITT standards.  
As we've discussed various terms, I'm pasting a "thousand words" to highlight conceptual components.

![image](https://user-images.githubusercontent.com/7647382/202588667-782e7227-ac9b-49f5-b740-0a2a27fd807d.png)

How do we finish this sentence:  
*The user will submit a signed statement/claim (see issue #34) to the ___*

1. The thing we're trying to name here, which is an implementation of a service.
2. The **eNotary** component that evaluates the Registration Policy (3) before proceeding
3. The **Registration Policy**, as the gatekeeper for what may be submitted to the ledger.
4. The **eNotary** counter signing key/service
5. The **ledger**, where statements/claims are persisted
6. The ledger of a ___ (1) may be implemented through various "ledger databases", such as [Azure CCF](https://azure.microsoft.com/en-us/products/azure-confidential-ledger/), [QLDB](https://aws.amazon.com/qldb/), [Trillian](https://github.com/google/trillian)

This issue is to discuss what we call (1)
Please "vote" with a comment, representing a number, and any supporting thoughts:

1. Transparency Service (with no acronym)
2. Registry
3. SCITT Implementation
4. Transparency Service (TS as a acronym)
5. _write in your own_

**Comment by fournet** [comment]
4. Transparency Service (TS as a acronym)

Please look at the existing terminology section before proposing global substitutions.

**Comment by henkbirkholz** [comment]
The substitution of TS to Transparency Services was due to comments that highlighted a possible confusion with Timestamp that would be intuitive to the generic reader.

Maybe let us split that decision out to the list and then fix this with a %s/foo/bar/g?

**Comment by SteveLasker** [comment]
Adding a link to a higher level overview @raylutz 
 assembled: https://docs.google.com/document/d/1qYljgugcraiamGjrhldQ1ZEoa4i_TkM3tzBg8yNzE_E/edit#

**Comment by SteveLasker** [comment]
Assigning to @raylutz for confirmation and update.

**Comment by SteveLasker** [comment]
Closing, due to inactivity and #16  and #8 cover open topics.
