### ISSUE TITLE
Add package.json for aasvg

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-scitt/draft-ietf-scitt-architecture#70]
Consider adding `package.json` for this repository so that people are able to use this without having `aasvg` locally installed.

See https://github.com/martinthomson/i-d-template/blob/main/doc/TOOLS.md#installing-dependencies-for-ci

**Comment by SteveLasker** [comment]
@henkbirkholz, this seems like a good suggestion. Any additional context as you're our "build master" with viz across multiple IETF drafts.

**Comment by SteveLasker** [comment]
closing as stale.
