### ISSUE TITLE
Add issue describing relative DID URLs

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#81]
based on https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/78/files#r1256894727

specifically the JSON and JSON-LD processing of the fragment part...

**Comment by SteveLasker** [comment]
@OR13, does #78 cover this issue?

**Comment by OR13** [comment]
Yes, I think we can close this one.
