### ISSUE TITLE
Add references to SBOM technologies

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-wg-scitt/draft-ietf-scitt-architecture#83]
The architecture draft lists a number of different SBOM technologies. References need to be added and acronymous expanded.
Yogesh volunteered to deal with this issue.

**Comment by yogeshbdeshpande** [comment]
@hannestschofenig I will work on this on return from my holidays...

**Comment by hannestschofenig** [comment]
ping

**Comment by yogeshbdeshpande** [comment]
ack: shall we attempt this today?
