### ISSUE TITLE
Requesting that existing software supply chain practice used in digital signatures be supported by SCITT

### ISSUE THREAD

**Issue by rjb4standards** [ietf-wg-scitt/draft-ietf-scitt-architecture#84]
As I mentioned during today's call. SCITT is entering into a large, established software supply chain corpus that uses common practices for digital signature verification, including PGP keys and X.509 digital certificates containing public keys. 
SCITT adoption of these existing practices will enable seamless adoption of SCITT. Failure to support existing software supply chain practices for digital signatures could prove to be a barrier to SCITT adoption.

Recommendation: Include support for current software supply chain digital signature practices within the SCITT Architecture.

**Comment by rjb4standards** [comment]
slight edit re seamless adoption

**Comment by OR13** [comment]
@rjb4standards here is how you would apply the same text we have for DIDs with COSE to DIDs with PGP:

*somewhere in your PGP signature meta data*, you would put:

`did:example:123#key-42` ... and it would need to `dereference` to :

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v4.10.9
Comment: https://openpgpjs.org
nxjMEYASIXxYJKwYBBAHaRw8BAQdAiEDH3eDo954hWbnf5srnHwL6WfTKXEwu
....
-----END PGP PUBLIC KEY BLOCK-----
```

Then anyone holding your `PGP Signed Message` would resolve the DID to get the key that verifiers the signature.

Instead of emailing someone your PGP key, you could email them the DID URL that they can use to dereference it.

This is similar to how you could send me your PGP key, or you could send me:

https://github.com/rjb4standards.gpg

A DID URL is just an identifier for a key, that people know how to resolve to the key.

Another example: https://github.com/or13.gpg

However, even if you have a PGP key, you will struggle to use it to verify anything other than PGP signatures.

**Comment by OR13** [comment]
BTW, here is a CLI that already supports what I am saying: https://github.com/OR13/lds-pgp2021/

But it applies to a data format that we don't use in SCITT, called W3C Verifiable Credentials.... We also don't use PGP Signatures in SCITT... but you could tunnel a PGP signature through a cose sign 1 signature as follows:


### Signed Statement Protected Header

```
{
  alg: ES384
  kid: did:example:123#key-42
  content_type: application/pgp-signature
}
```

### Signed Statement Protected Payload

```
-----BEGIN PGP SIGNATURE-----

iQEzBAABCAAdFiEET9QBfWGI/5tPBymeAv7M1jBvKZwFAmAE1TkACgkQAv7M1jBv
....
-----END PGP SIGNATURE-----
```

**Comment by OR13** [comment]
You can also do the same with W3C Verifiable Credentials:


### Signed Statement Protected Header

```
{
  alg: ES384
  kid: did:example:123#key-42
  content_type: application/vc+ld+jwt
}
```

### Signed Statement Protected Payload

```
eyJhbGciOiJFUzM4NCIsInR5cCI6InZjK2xkK2p3dCIsImlzcyI6ImRpZDp3ZWI6Y29udG9zby5
leGFtcGxlIiwiaWF0IjoxNjg4MTU1NDg2fQ.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5
vcmcvbnMvY3JlZGVudGlhbHMvdjIiLCJodHRwczovL3d3dy53My5vcmcvbnMvY3JlZGVudGlhbH
MvZXhhbXBsZXMvdjIiXSwiaWQiOiJodHRwczovL2NvbnRvc28uZXhhbXBsZS9jcmVkZW50aWFsc
y8zNTMyNzI1NSIsInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJLWUNFeGFtcGxlIl0s
Imlzc3VlciI6ImRpZDp3ZWI6Y29udG9zby5leGFtcGxlIiwidmFsaWRGcm9tIjoiMjAxOS0wNS0
yNVQwMzoxMDoxNi45OTJaIiwidmFsaWRVbnRpbCI6IjIwMjctMDUtMjVUMDM6MTA6MTYuOTkyWi
IsImNyZWRlbnRpYWxTY2hlbWEiOnsiaWQiOiJodHRwczovL2NvbnRvc28uZXhhbXBsZS9iYWZ5Y
mVpZ2R5ci4uLmxxYWJmM29jbGd0cXk1NWZiemRpIiwidHlwZSI6Ikpzb25TY2hlbWEifSwiY3Jl
ZGVudGlhbFN1YmplY3QiOnsiaWQiOiJkaWQ6ZXhhbXBsZToxMjMxNTg4IiwidHlwZSI6IlBlcnN
vbiJ9fQ.Mc6KqMurMIl2XfqY9_4abKvBJszOHEz4wQhHckwbVnkcb2cI1OH7JCu-YL9PK9-5_CA
4egZZoM6yOr7FyOtOCHQFFaK-GNmtCAz-ydJGd6827u28B4pAbyk6ceJjmVWL
```

**Comment by OR13** [comment]
@rjb4standards I'm not really an expert on JOSE or COSE x509, 

See: https://datatracker.ietf.org/doc/html/rfc9360#name-x509-cose-header-parameters

But I think something like this would solve it:

### Signed Statement Protected Header

```
{
  alg: ES384
  x5chain: ....
  x5t: ....
  x5u: ...
  content_type: application/spdx+json
}
```

### Signed Statement Protected Payload

```
.... 
```

**Comment by rjb4standards** [comment]
I’ve provided an X.509 example to consider:

 

 



 

Thanks,

 

Dick Brooks

  

Active Member of the CISA Critical Manufacturing Sector, 

Sector Coordinating Council – A Public-Private Partnership

 

 <https://reliableenergyanalytics.com/products> Never trust software, always verify and report! ™

 <http://www.reliableenergyanalytics.com/> http://www.reliableenergyanalytics.com

Email:  ***@***.***> ***@***.***

Tel: +1 978-696-1788
