### ISSUE TITLE
REST API Thoughts

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#86]
## Key From Message

POST key.trans.scitt/resolve/verification-key
{ ... prefer detached siganture }
---content-type application/jwt            --> application/jwk+json
---content-type application/cwt            --> application/cose-key
---content-type application/pgp-signature  --> application/pgp-keys
---content-type application/vc+ld+json     --> application/did+ld+json
---content-type application/vc+json        --> application/did+json
---content-type application/vc+sd-jwt      --> application/did+json
---content-type application/vc+sd-jwt      --> application/jwk+json

... cache public key locally indexed by meta data (iss, kid) ...

... verify offline from cache

## Feed ( Assertion Keys ) From Verified Messages

GET key.trans.scitt/ {iss}   /verification-keys 
  -> feed of all public keys witnessed verifying signed statements for "iss" or "kid" ...

Do we want these? https://www.w3.org/TR/did-core/#verification-relationships

## Feed ( Artifact Statements ) From Verified Messages

GET key.trans.scitt/ {iss}   /gtin/01/9506000134352
  -> feed of all related signed statements from "iss" or "kid" ...

Generic feed URL structure:

{iss} / {topic}
      ? {filters} 
      # {client-hint}

did:example:123/gtin/01/9506000134352?origin-country=US#product-name

Generic values for iss:

Domain: example.com
DID: did:example:123
... ?

**Comment by OR13** [comment]
Related to `vc` or `vc+ld+jwt`... https://openid.net/specs/openid-connect-userinfo-vc-1_0.html#name-userinfo-vc-verification

**Comment by SteveLasker** [comment]
Should this move to [SCRAPI}(https://github.com/ietf-scitt/draft-birkholz-scitt-scrapi/)

**Comment by SteveLasker** [comment]
Closing. Please reactivate, or open in SCRAPI
