### ISSUE TITLE
Document key discovery for OIDC

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#87]
@Sakurann mentioned we should reference more, and repeat or "redefine" less.... I agree.

We can possibly refer to this: 

- https://openid.net/specs/openid-connect-userinfo-vc-1_0.html#name-userinfo-vc-verification

**Comment by pdxjohnny** [comment]
How do we see OIDC working with SCITT other than for auth? I'm having trouble understanding how we could use a token as the issuer of a claim. It seems like that would immediately leak the token upon insertion to the log.

**Comment by SteveLasker** [comment]
Moved to https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/138 in SCRAPI
