### ISSUE TITLE
Harmonize Terms "Auditor", "Consumer" and "Verifier"

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-wg-scitt/draft-ietf-scitt-architecture#89]
I think it would be better to use one common term for these roles since they are currently not well defined. For the specification work it does not matter whether an auditor, consumer or a verifier checks the append-only log.

Using only one term simplifies the document.

**Comment by nealmcb** [comment]
We build on [RFC 9162 - Certificate Transparency Version 2.0](https://datatracker.ietf.org/doc/html/rfc9162) (CT) in various ways. CT defines the roles of "monitor" and "auditor":

*   Monitors watch logs to check for correct behavior, for certificates of interest, or for both. For example, a monitor may be configured to report on all certificates that apply to a specific domain name when fetching new entries for consistency validation.

* Auditing ensures that the current published state of a log is reachable from previously published states that are known to be good and that the promises made by the log, in the form of SCTs, have been kept. Audits are performed by monitors or TLS clients.

I'm not up-to-date, but it would seem useful to define how the ecosystem can gain confidence that SCITT transparency logs are following the append-only rules, perhaps via similar roles as used in CT. Such client use cases may well have some different requirements for various aspects of the architecture or APIs, than what I'll call "relying parties" who are concerned with verifying a specific claim.

**Comment by SteveLasker** [comment]
Closing, as the current 04 draft moved to Auditor and Verifier. 
There's additional debate, but this appears to be complete as those terms were adopted (per the title)
