### ISSUE TITLE
The use of "SHOULD" throughout the spec

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-wg-scitt/draft-ietf-scitt-architecture#91]
The specification uses the RFC 2119 "SHOULD" all over the place. A SHOULD needs to come with a description of when the developer should follow it and when it is not appropriate. Too many SHOULDs do not help with interoperability.

Also, check the use of normative language: Is it possible to create a test case that will help to improve interoperability?

For example, in the following sentence the use of the SHOULD is not useful:

"
Issuers SHOULD use consistent decentralized identifiers for all their Statements about Artifacts, to simplify authorization by Verifiers and auditing.
"

The reader might ask themselves:

* When should I use "inconsistent decentralized identifiers"?
* What is a consistent decentralized identifier?

Here is another sentence:

"
Issuers MAY choose the DID method they prefer, but with no guarantee that all Transparency Services will be able to register their Signed Statements. To facilitate interoperability, all Transparency Service implementations SHOULD support the did:web method [[DID-WEB](https://w3c-ccg.github.io/did-method-web/)].
"

Why is there a SHOULD in this sentence instead of a MUST? If you want to accomplish interoperability you have to put a MUST there.

**Comment by ad-l** [comment]
See #95
