### ISSUE TITLE
Discovery of service parameters

### ISSUE THREAD

**Issue by pdxjohnny** [ietf-wg-scitt/draft-ietf-scitt-architecture#96]
Knowledge of SCITT's tree algorithm and parameters for that tree algorithm are required for a client to verify receipts. It seems like we need to have an endpoint to enable discovery of those parameters.

**Comment by pdxjohnny** [comment]
Nevermind the client code just need to get the tree alg from the receipt.

**Comment by pdxjohnny** [comment]
Related: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/79#issuecomment-1767570492

**Comment by pdxjohnny** [comment]
After discussion this weekend with Steven and Cedric we talked about needing an endpoint for service parameter discovery.

**Comment by pdxjohnny** [comment]
The document currently states:

> The Transparency Service provides an endpoint that returns the Transparent Statement that describes its current configuration."
>
> The Transparency Service records its configuration in the Append-Only Log using Transparent Statements with distinguished media type `application/scitt-configuration`.
>
> From: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/blob/930a0cd38a92dd6079bda2ed3c675019ee9b0aa3/draft-ietf-scitt-architecture.md#configuration

Pining based on #126 discussion comments: @fournet, @SteveLasker: I read this to mean the endpoint is a subject/feed, what is that subject/feed? Is it the issuer `did:web:` combined with the mentioned media type? How should we register these so that they are discoverable in a consistent way?

**Comment by SteveLasker** [comment]
Queue to move to the SCRAPI repo
