### ISSUE TITLE
Using only qualified "Issuers" for clarity

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-wg-scitt/draft-ietf-scitt-architecture#97]
We should consider to use "Statement Issuer" and "Receipt Issuer" consistently instead of allowing for using stand-alone "issuer" - for better clarity.
Base on Orie's comment: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/95/files#r1308908322

**Comment by OR13** [comment]
cross linking other issues with context:

- https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/65
- https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/8
- https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/23
- https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/issues/97

**Comment by OR13** [comment]
I suggest the following changes to the architecture:

1. Revise "issuer" in terminology, and align it to "iss".
2. Add "Statement Issuer" and "Receipt Issuer" to terminology, and clarify that they both rely on `iss`, and reflect the identifier of the entity making statements about artifacts and the entity making those statements transparent (aka the transparency service).
3. Clarify that `iss` MUST be a DID.
4. Clarify that `kid` MUST be a relative DID URL which `iss` as the base.

**Comment by fournet** [comment]
1. Why is it important to align to "iss"? 
2. For now we use "Transparency Service" instead of "Receipt Issuer". Are you suggesting we merge the two? Otherwise where do we need to explicitly write "Receipt Issuer" in SCITT? 
3. Ok
4. Does it apply both to statement signatures and receipts?

**Comment by SteveLasker** [comment]
Closing as stale. Please reopen if need for the current draft
