### ISSUE TITLE
Adjust language in PR

### ISSUE THREAD

**Issue by OR13** [ietf-wg-scitt/draft-ietf-scitt-architecture#99]
I don't love the language we added in:

> If an issuer uses multiple DIDs (for instance, because their clients support different resolution methods), they MUST ensure that statements signed under each DID are consistent.

https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/95#discussion_r1308967013

I said:

> The verifier is interested in the authenticity of the issuer of the transparent statement and signed statement... The verifier trusts the TS to vet the issuer of the signed statement... the verifier benefits from the transparency service, if they can't trust the TS, there is no reason to do SCITT.

**Comment by OR13** [comment]
I suggest we remove the MUST here, and just say that verifiers are required to trust all issuer keys associated with issuer identifiers, in order to perform their role.

**Comment by SteveLasker** [comment]
@OR13, I just saw this. Can you this to a PR, and maybe update the Title of this issue?

**Comment by OR13** [comment]
I think the whole section on DIDs needs to be reworked.

Also the VCWG is currently trying to generalize the concept of DIDs to controller documents... And I'm starting to feel that perhaps it's better to remove references to them entirely.

**Comment by SteveLasker** [comment]
Closing, with the request to open a specific issue to DIDs, or build on #117 or #36

**Comment by SteveLasker** [comment]
Believe this was resolved in #107, here: https://github.com/ietf-wg-scitt/draft-ietf-scitt-architecture/pull/107/files#diff-585fb424519b79cf000445f3425fa56d328cbaca5d2a622740ddc4e5ca91dbe1R497

**Comment by SteveLasker** [comment]
Accidental re-open for the wrong issue
